# image will be published to ghcr.io/<user>/<name>
name: nimbus-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/ubuntu-fonts/repo/fedora-%OS_VERSION%/atim-ubuntu-fonts-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - powerline-go
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      # all evince related libraries are already installed, don't see the benefit on installing it via flatpak
      - evince
      # *I think* flatpak simple-scan only works with driverless scanners, probably better to keep it layered
      - simple-scan
      # additional fonts
      - ubuntu-family-fonts
      - fira-code-fonts
      - cascadia-code-nf-fonts
      - java-17-openjdk
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - gnome-software-rpm-ostree
      - virtualbox-guest-additions

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Contacts
        - org.gnome.Loupe
        - org.gnome.NautilusPreviewer
        - org.gnome.TextEditor
        - com.github.rafostar.Clapper
        - org.gnome.FileRoller
        - com.github.tchx84.Flatseal
        - io.gitlab.adhami3310.Impression
        - org.libreoffice.LibreOffice
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: gschema-overrides
    include:
      - zz1-nimbus.gschema.override
  
  - type: justfiles

  - type: script
    scripts:
      - install_autofirma.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

