modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - simple-scan
      - powerline-go
      - gnome-shell-extension-appindicator
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - gnome-software-rpm-ostree
      - virtualbox-guest-additions

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: fonts
    fonts:
      nerd-fonts:
        - Ubuntu
        - FiraCode
        - CascadiaCode

  - type: yafti
    custom-flatpaks:
      - Clapper: com.github.rafostar.Clapper
      - FileRoller: org.gnome.FileRoller
      - Gnome Firmware: org.gnome.Firmware
      - Geary: org.gnome.Geary
      - Dropbox: com.dropbox.Client
      - Impression: io.gitlab.adhami3310.Impression
      - Gimp: org.gimp.GIMP
      - Inkscape: org.inkscape.Inkscape
      - Darktable: org.darktable.Darktable
      - Fractal: org.gnome.Fractal
      - Telegram: org.telegram.desktop
      - Fragments: de.haeckerfelix.Fragments
      - Pitivi: org.pitivi.Pitivi
      - Kdenlive: org.kde.kdenlive
      - Spotify: com.spotify.Client
      - Spot: dev.alextren.Spot

  - type: gschema-overrides
    include:
      - zz1-nimbus.gschema.override