title: Welcome to uBlue
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to uBlue (Alpha)"
      icon: "/path/to/icon"
      description: |
        This guided installer will help you get started with your new system.
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: false
        system: true
      groups:
        System Apps:
          description: System applications for all desktop environments.
          default: false
          packages:
            - Mission Center: io.missioncenter.MissionCenter
        Web Browsers:
          description: Additional browsers to complement or replace Firefox.
          default: false
          packages:
            - Mozilla Firefox: org.mozilla.firefox
            - GNOME Web: org.gnome.Epiphany
            - Google Chrome: com.google.Chrome
        Multimedia:
          description: Multimedia applications (graphics and video)
          default: false
          packages:
            - Gimp: org.gimp.GIMP
            - Inkscape: org.inkscape.Inkscape
            - Darktable: org.darktable.Darktable
            - Pitivi: org.pitivi.Pitivi
            - Kdenlive: org.kde.kdenlive
            - Spotify: com.spotify.Client
            - Spot: dev.alextren.Spot
        Gaming:
          description: "Rock and Stone!"
          default: false
          packages:
            - Bottles: com.usebottles.bottles
            - Discord: com.discordapp.Discord
            - Heroic Games Launcher: com.heroicgameslauncher.hgl
            - Steam: com.valvesoftware.Steam
            - Gamescope (Utility): org.freedesktop.Platform.VulkanLayer.gamescope
            - MangoHUD (Utility): org.freedesktop.Platform.VulkanLayer.MangoHud//22.08
            - SteamTinkerLaunch (Utility): com.valvesoftware.Steam.Utility.steamtinkerlaunch
            - Proton Updater for Steam: net.davidotek.pupgui2
        Office:
          description: Boost your productivity.
          default: false
          packages:
            - LibreOffice: org.libreoffice.LibreOffice
            - OnlyOffice: org.onlyoffice.desktopeditors
            - Obsidian: md.obsidian.Obsidian
            - Slack: com.slack.Slack
            - Standard Notes: org.standardnotes.standardnotes
            - Thunderbird Email: org.mozilla.Thunderbird
            - Geary Email: org.gnome.Geary
            - Dropbox: com.dropbox.Client
        Streaming:
          description: Stream to the Internet.
          default: false
          packages:
            - OBS Studio: com.obsproject.Studio
            - VkCapture for OBS: com.obsproject.Studio.OBSVkCapture
            - Gstreamer for OBS: com.obsproject.Studio.Plugin.Gstreamer
            - Gstreamer VAAPI for OBS: com.obsproject.Studio.Plugin.GStreamerVaapi
            - Boatswain for Streamdeck: com.feaneron.Boatswain
        Development:
          description: Development applications
          default: false
          packages:
            - Gnome Builder: org.gnome.Builder
            - Cockpit Client: org.cockpit_project.CockpitClient
            - Meld: org.gnome.meld
            - Gitg: org.gnome.gitg
        Misc:
          description: Different utilities and applications
          default: false
          packages:
            - Fractal: org.gnome.Fractal
            - Telegram: org.telegram.desktop
            - Fragments: de.haeckerfelix.Fragments
            - Deja Dup Backups: org.gnome.DejaDup
            - Fedora Media Writer: org.fedoraproject.MediaWriter
            - Font Downloader: org.gustavoperedo.FontDownloader

  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Applications":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://ublue.it
        - "Join the Discord Community":
            run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Thanks for trying uBlue, we hope you enjoy it!